---
version: '3.8'

services:
  localstack:
    ports:
      - "4566:4566"
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=ABC
      - AWS_DEFAULT_REGION=us-east-1
